// Implementation file for parser generated by fsyacc
module InputParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 2 "InputParser.fsp"

open InputTypesAST

# 10 "InputParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | WHITESPACE
  | LCBRACK
  | RCBRACK
  | ZERO
  | PLUS
  | MINUS
  | SIGN of (char)
  | ASSIGN
  | LBRACK
  | RBRACK
  | SEPARATOR
  | ARRAY of (char)
  | VAR of (string)
  | NUM of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_WHITESPACE
    | TOKEN_LCBRACK
    | TOKEN_RCBRACK
    | TOKEN_ZERO
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_SIGN
    | TOKEN_ASSIGN
    | TOKEN_LBRACK
    | TOKEN_RBRACK
    | TOKEN_SEPARATOR
    | TOKEN_ARRAY
    | TOKEN_VAR
    | TOKEN_NUM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_expr
    | NONTERM_conExpr
    | NONTERM_conArrElement
    | NONTERM_absExpr
    | NONTERM_absArrElement

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | WHITESPACE  -> 1 
  | LCBRACK  -> 2 
  | RCBRACK  -> 3 
  | ZERO  -> 4 
  | PLUS  -> 5 
  | MINUS  -> 6 
  | SIGN _ -> 7 
  | ASSIGN  -> 8 
  | LBRACK  -> 9 
  | RBRACK  -> 10 
  | SEPARATOR  -> 11 
  | ARRAY _ -> 12 
  | VAR _ -> 13 
  | NUM _ -> 14 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_WHITESPACE 
  | 2 -> TOKEN_LCBRACK 
  | 3 -> TOKEN_RCBRACK 
  | 4 -> TOKEN_ZERO 
  | 5 -> TOKEN_PLUS 
  | 6 -> TOKEN_MINUS 
  | 7 -> TOKEN_SIGN 
  | 8 -> TOKEN_ASSIGN 
  | 9 -> TOKEN_LBRACK 
  | 10 -> TOKEN_RBRACK 
  | 11 -> TOKEN_SEPARATOR 
  | 12 -> TOKEN_ARRAY 
  | 13 -> TOKEN_VAR 
  | 14 -> TOKEN_NUM 
  | 17 -> TOKEN_end_of_input
  | 15 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_expr 
    | 3 -> NONTERM_expr 
    | 4 -> NONTERM_conExpr 
    | 5 -> NONTERM_conExpr 
    | 6 -> NONTERM_conExpr 
    | 7 -> NONTERM_conArrElement 
    | 8 -> NONTERM_conArrElement 
    | 9 -> NONTERM_absExpr 
    | 10 -> NONTERM_absExpr 
    | 11 -> NONTERM_absArrElement 
    | 12 -> NONTERM_absArrElement 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 17 
let _fsyacc_tagOfErrorTerminal = 15

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | WHITESPACE  -> "WHITESPACE" 
  | LCBRACK  -> "LCBRACK" 
  | RCBRACK  -> "RCBRACK" 
  | ZERO  -> "ZERO" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | SIGN _ -> "SIGN" 
  | ASSIGN  -> "ASSIGN" 
  | LBRACK  -> "LBRACK" 
  | RBRACK  -> "RBRACK" 
  | SEPARATOR  -> "SEPARATOR" 
  | ARRAY _ -> "ARRAY" 
  | VAR _ -> "VAR" 
  | NUM _ -> "NUM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | WHITESPACE  -> (null : System.Object) 
  | LCBRACK  -> (null : System.Object) 
  | RCBRACK  -> (null : System.Object) 
  | ZERO  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | SIGN _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ASSIGN  -> (null : System.Object) 
  | LBRACK  -> (null : System.Object) 
  | RBRACK  -> (null : System.Object) 
  | SEPARATOR  -> (null : System.Object) 
  | ARRAY _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | VAR _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 2us; 65535us; 0us; 5us; 19us; 18us; 2us; 65535us; 15us; 16us; 21us; 22us; 1us; 65535us; 0us; 4us; 2us; 65535us; 24us; 25us; 28us; 29us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 8us; 11us; 13us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 1us; 2us; 2us; 3us; 6us; 1us; 4us; 2us; 4us; 9us; 1us; 4us; 2us; 4us; 9us; 1us; 4us; 1us; 5us; 2us; 5us; 10us; 1us; 5us; 2us; 5us; 10us; 1us; 5us; 1us; 5us; 1us; 5us; 2us; 6us; 6us; 1us; 6us; 2us; 7us; 8us; 1us; 8us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 10us; 1us; 10us; 2us; 11us; 12us; 1us; 12us; 1us; 12us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 13us; 15us; 18us; 20us; 23us; 25us; 27us; 30us; 32us; 35us; 37us; 39us; 41us; 44us; 46us; 49us; 51us; 53us; 55us; 57us; 59us; 61us; 64us; 66us; |]
let _fsyacc_action_rows = 30
let _fsyacc_actionTableElements = [|2us; 32768us; 12us; 12us; 13us; 7us; 0us; 49152us; 1us; 32768us; 0us; 3us; 0us; 16385us; 0us; 16386us; 1us; 16387us; 11us; 19us; 1us; 32768us; 8us; 8us; 1us; 32768us; 8us; 9us; 1us; 32768us; 14us; 10us; 2us; 32768us; 7us; 23us; 14us; 10us; 0us; 16388us; 1us; 32768us; 8us; 13us; 1us; 32768us; 8us; 14us; 1us; 32768us; 9us; 15us; 2us; 32768us; 2us; 24us; 9us; 15us; 1us; 32768us; 14us; 20us; 1us; 32768us; 10us; 17us; 0us; 16389us; 1us; 16390us; 11us; 19us; 2us; 32768us; 12us; 11us; 13us; 6us; 1us; 16391us; 11us; 21us; 1us; 32768us; 14us; 20us; 0us; 16392us; 0us; 16393us; 1us; 32768us; 7us; 27us; 1us; 32768us; 3us; 26us; 0us; 16394us; 1us; 16395us; 11us; 28us; 1us; 32768us; 7us; 27us; 0us; 16396us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 6us; 7us; 8us; 10us; 12us; 14us; 16us; 19us; 20us; 22us; 24us; 26us; 29us; 31us; 33us; 34us; 36us; 39us; 41us; 43us; 44us; 45us; 47us; 49us; 50us; 52us; 54us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 1us; 3us; 5us; 3us; 1us; 3us; 3us; 5us; 1us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 3us; 4us; 4us; 5us; 5us; 6us; 6us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 65535us; 65535us; 65535us; 65535us; 65535us; 16388us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16389us; 65535us; 65535us; 65535us; 65535us; 16392us; 16393us; 65535us; 65535us; 16394us; 65535us; 65535us; 16396us; |]
let _fsyacc_reductions ()  =    [| 
# 167 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : init)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 176 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : init)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "InputParser.fsp"
                                                   _1 
                   )
# 42 "InputParser.fsp"
                 : init));
# 187 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : absElement)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "InputParser.fsp"
                                                                      init(_1)
                   )
# 53 "InputParser.fsp"
                 : init));
# 198 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : conElement)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "InputParser.fsp"
                                                                      init(_1)
                   )
# 54 "InputParser.fsp"
                 : init));
# 209 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "InputParser.fsp"
                                                                    ConVar(_1, _3)           
                   )
# 56 "InputParser.fsp"
                 : conElement));
# 221 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : char)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : conArrContent)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "InputParser.fsp"
                                                                          ConArr(_1, _4)           
                   )
# 57 "InputParser.fsp"
                 : conElement));
# 233 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : conElement)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : conElement)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "InputParser.fsp"
                                                                        ConSeq(_1, _3)           
                   )
# 58 "InputParser.fsp"
                 : conElement));
# 245 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 60 "InputParser.fsp"
                                                                    NumElem(_1)     
                   )
# 60 "InputParser.fsp"
                 : conArrContent));
# 256 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : conArrContent)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "InputParser.fsp"
                                                                          Elems(_1, _3)   
                   )
# 61 "InputParser.fsp"
                 : conArrContent));
# 268 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : char)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "InputParser.fsp"
                                                                AbsVar(_1, _3)       
                   )
# 63 "InputParser.fsp"
                 : absElement));
# 280 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : char)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : absArr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "InputParser.fsp"
                                                                          AbsArr(_1, _4)       
                   )
# 64 "InputParser.fsp"
                 : absElement));
# 292 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : char)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 66 "InputParser.fsp"
                                                                    SignElem(_1)         
                   )
# 66 "InputParser.fsp"
                 : absArr));
# 303 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : char)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : absArr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "InputParser.fsp"
                                                                  SignArrElems(_1, _3)  
                   )
# 67 "InputParser.fsp"
                 : absArr));
|]
# 316 "InputParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 18;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : init =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
