// Implementation file for parser generated by fsyacc
module SecurityParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 2 "SecurityParser.fsp"

open SecurityTypesAST

# 10 "SecurityParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | WHITESPACE
  | ASSIGN
  | LtSEPARATOR
  | SEPARATOR
  | ARRAY of (char)
  | VAR of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_WHITESPACE
    | TOKEN_ASSIGN
    | TOKEN_LtSEPARATOR
    | TOKEN_SEPARATOR
    | TOKEN_ARRAY
    | TOKEN_VAR
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_init
    | NONTERM_securityLattice
    | NONTERM_securityClassification

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | WHITESPACE  -> 1 
  | ASSIGN  -> 2 
  | LtSEPARATOR  -> 3 
  | SEPARATOR  -> 4 
  | ARRAY _ -> 5 
  | VAR _ -> 6 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_WHITESPACE 
  | 2 -> TOKEN_ASSIGN 
  | 3 -> TOKEN_LtSEPARATOR 
  | 4 -> TOKEN_SEPARATOR 
  | 5 -> TOKEN_ARRAY 
  | 6 -> TOKEN_VAR 
  | 9 -> TOKEN_end_of_input
  | 7 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_init 
    | 3 -> NONTERM_init 
    | 4 -> NONTERM_securityLattice 
    | 5 -> NONTERM_securityLattice 
    | 6 -> NONTERM_securityClassification 
    | 7 -> NONTERM_securityClassification 
    | 8 -> NONTERM_securityClassification 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 9 
let _fsyacc_tagOfErrorTerminal = 7

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | WHITESPACE  -> "WHITESPACE" 
  | ASSIGN  -> "ASSIGN" 
  | LtSEPARATOR  -> "LtSEPARATOR" 
  | SEPARATOR  -> "SEPARATOR" 
  | ARRAY _ -> "ARRAY" 
  | VAR _ -> "VAR" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | WHITESPACE  -> (null : System.Object) 
  | ASSIGN  -> (null : System.Object) 
  | LtSEPARATOR  -> (null : System.Object) 
  | SEPARATOR  -> (null : System.Object) 
  | ARRAY _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | VAR _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 2us; 65535us; 0us; 4us; 11us; 10us; 2us; 65535us; 0us; 5us; 19us; 18us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 8us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 2us; 2us; 5us; 2us; 3us; 8us; 1us; 4us; 2us; 4us; 6us; 1us; 4us; 1us; 4us; 2us; 5us; 5us; 1us; 5us; 1us; 6us; 1us; 6us; 1us; 6us; 1us; 7us; 1us; 7us; 1us; 7us; 2us; 8us; 8us; 1us; 8us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 11us; 14us; 16us; 19us; 21us; 23us; 26us; 28us; 30us; 32us; 34us; 36us; 38us; 40us; 43us; |]
let _fsyacc_action_rows = 20
let _fsyacc_actionTableElements = [|2us; 32768us; 5us; 15us; 6us; 7us; 0us; 49152us; 1us; 32768us; 0us; 3us; 0us; 16385us; 1us; 16386us; 4us; 11us; 1us; 16387us; 4us; 19us; 1us; 32768us; 3us; 8us; 2us; 32768us; 2us; 13us; 3us; 8us; 1us; 32768us; 6us; 9us; 0us; 16388us; 1us; 16389us; 4us; 11us; 1us; 32768us; 6us; 6us; 1us; 32768us; 2us; 13us; 1us; 32768us; 6us; 14us; 0us; 16390us; 1us; 32768us; 2us; 16us; 1us; 32768us; 6us; 17us; 0us; 16391us; 1us; 16392us; 4us; 19us; 2us; 32768us; 5us; 15us; 6us; 12us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 6us; 7us; 9us; 11us; 13us; 16us; 18us; 19us; 21us; 23us; 25us; 27us; 28us; 30us; 32us; 33us; 35us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 1us; 3us; 3us; 3us; 3us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 4us; 4us; 4us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 65535us; 65535us; 65535us; 65535us; 65535us; 16388us; 65535us; 65535us; 65535us; 65535us; 16390us; 65535us; 65535us; 16391us; 65535us; 65535us; |]
let _fsyacc_reductions ()  =    [| 
# 113 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Choice)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 122 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Choice)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "SecurityParser.fsp"
                                                   _1 
                   )
# 36 "SecurityParser.fsp"
                 : Choice));
# 133 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : SecurityLattice)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "SecurityParser.fsp"
                                                                                        SecurityLatInit(_1) 
                   )
# 47 "SecurityParser.fsp"
                 : Choice));
# 144 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : SecurityClassification)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "SecurityParser.fsp"
                                                                                        SecurityClassInit(_1) 
                   )
# 48 "SecurityParser.fsp"
                 : Choice));
# 155 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "SecurityParser.fsp"
                                                                                        Level(_1,_3) 
                   )
# 50 "SecurityParser.fsp"
                 : SecurityLattice));
# 167 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : SecurityLattice)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : SecurityLattice)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "SecurityParser.fsp"
                                                                                        MulLevel(_1,_3) 
                   )
# 51 "SecurityParser.fsp"
                 : SecurityLattice));
# 179 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "SecurityParser.fsp"
                                                                                       InitVar(_1, _3) 
                   )
# 53 "SecurityParser.fsp"
                 : SecurityClassification));
# 191 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : char)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "SecurityParser.fsp"
                                                                                       InitArr(_1, _3) 
                   )
# 54 "SecurityParser.fsp"
                 : SecurityClassification));
# 203 "SecurityParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : SecurityClassification)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : SecurityClassification)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "SecurityParser.fsp"
                                                                                       InitSeq(_1, _3) 
                   )
# 55 "SecurityParser.fsp"
                 : SecurityClassification));
|]
# 216 "SecurityParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 10;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : Choice =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
